version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            sudo pip install pipenv==2018.05.18
            pipenv install --dev
      - run:
          name: Run tests
          command: |
            mkdir -p test-reports/
            pipenv run pytest --cov=projet -vv projet.py --junitxml=test-reports/junit.xml
      - store_test_results:
          path: test-reports
